# Site settings
title:          Jesse Millar
description:    "Devlog"
baseurl:        "/devlog"
url:            "https://jessemillar.github.io"

# Google Analytics
google_analytics: UA-56479946-1

# Author
author:
  name:         Jesse Millar
  url:          https://jessemillar.com
  email:        hellojessemillar@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /:title
paginate:       5
